export const SET_COMPARE_VAULTS = 'SET_COMPARE_VAULTS';

export const SET_COMPARE_VAULTS_LIST = 'SET_COMPARE_VAULTSLIST';

export const SET_FILTER_DATA = 'SET_FILTER_DATA';

export const SET_AVAILABLE_VAULT = 'SET_AVAILABLE_VAULT';

export const SET_SORT_DATA = 'SET_SORT_DATA';

export const SET_VIEW_DATA = 'SET_VIEW_DATA';

export const SET_OVERVIEW = 'SET_OVERVIEW';
