export const ORACLE_DEVNET_ADDR = 'BmA9Z6FjioHJPpjT39QazZyhDRUdZy2ezwx4GiDdE2u2';
export const ORACLE_TESTNET_ADDR = 'AFmdnt9ng1uVxqCmqwQJDAYC5cKTkw8gJKSM5PnzuF6z';
export const ORACLE_MAINNET_ADDR = 'AHtgzX45WTKfkPG53L6WYhGEXwQkN1BVknET3sVsLL8J';
